name: Frame-Stats-Example
author: Paul2708
version: 0.0.1
main: de.paul2708.framestats.example.FrameStatsPlugin
api-version: '1.8'
depend: [ProtocolLib]
commands:
  search:
    description: Search for a name
  update:
    description: Update the table